train:
  average_best_models: true
  warmup_mode: linear_epoch_step
  warmup_initial_lr: 1e-6
  lr_warmup_epochs: 3
  initial_lr: 5e-4
  lr_mode: cosine
  cosine_final_lr_ratio: 0.1
  optimizer: AdamW
  optimizer_params:
    weight_decay: 0.0001
  zero_weight_decay_on_bias_and_bn: true
  ema: true
  ema_params:
    decay: 0.9
    decay_type: threshold
  max_epochs: 30
  mixed_precision: true
  loss:
    type: PPYoloELoss
    use_static_assigner: false
    num_classes: 1  # Update based on your number of classes
    reg_max: 16
  valid_metrics_list:
    - type: DetectionMetrics_050
      score_thres: 0.1
      top_k_predictions: 300
      num_cls: 1  # Update based on your number of classes
      normalize_targets: true
      post_prediction_callback:
        type: PPYoloEPostPredictionCallback
        score_threshold: 0.01
        nms_top_k: 1000
        max_predictions: 300
        nms_threshold: 0.7
  metric_to_watch: mAP@0.50




engine\trainer: task=detect, mode=train, model=archive/weights/yolov10x.pt, data=data.yaml, epochs=25, time=None, patience=100, batch=32, imgsz=640, save=True, save_period=-1, val_period=1, cache=False, device=None, workers=8, project=None, name=train17, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\train17
