artifact_location: file:///c:/Users/SaiRamPenjarla/Desktop/Project/YOLOV10/runs/mlflow/0
creation_time: 1717415771161
experiment_id: '0'
last_update_time: 1717415771161
lifecycle_stage: active
name: Default
